<a href="https://colab.research.google.com/github/nadhilafira/UAS-Probstok/blob/master/SourceCodeStockPrediction_NadhilaFakhira_1706043033.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [105]:
import plotly.graph_objs as go
import plotly.tools as tools
import plotly.figure_factory as FF
import plotly as py
import numpy as np
import pandas as pd
import scipy

data1 = pd.read_csv (r'https://raw.githubusercontent.com/nadhilafira/Nikkei/master/Nikkei.csv')
data2 = pd.read_csv(r'https://raw.githubusercontent.com/nadhilafira/Nikkei/master/Unilever.csv')
data3 = pd.read_csv(r'https://raw.githubusercontent.com/nadhilafira/Nikkei/master/SEL.csv')

data1.head()

Date          Open          High  ...         Close     Adj Close  Volume
0  2014-12-08  18004.660156  18030.830078  ...  17935.640625  17935.640625  134700
1  2014-12-09  17820.240234  17892.160156  ...  17813.380859  17813.380859  140400
2  2014-12-10  17623.349609  17658.140625  ...  17412.580078  17412.580078  169600
3  2014-12-11  17180.490234  17289.730469  ...  17257.400391  17257.400391  151400
4  2014-12-12  17317.689453  17526.189453  ...  17371.580078  17371.580078  214500

[5 rows x 7 columns]

In [54]:
data2.head()

Date     Open     High      Low    Close     Adj Close   Volume
0  2014-12-08  31700.0  31700.0  31050.0  31150.0  28040.568359  1240100
1  2014-12-09  31000.0  31175.0  30975.0  31025.0  27928.044922  1608000
2  2014-12-10  31025.0  31125.0  31000.0  31100.0  27995.562500   872800
3  2014-12-11  31075.0  31075.0  30900.0  30900.0  27815.523438  2589800
4  2014-12-12  30900.0  31050.0  30900.0  30975.0  27883.041016  1010400

In [106]:
data3.head()

Date  Open  High   Low  Close  Adj Close   Volume
0  2014-12-08  7.29  7.37  7.29   7.35   6.046041  1452000
1  2014-12-09  7.37  7.65  7.37   7.60   6.251688  8078000
2  2014-12-10  7.60  7.60  7.51   7.60   6.251688  4322000
3  2014-12-11  7.60  7.61  7.57   7.59   6.243463  2292800
4  2014-12-12  7.60  7.71  7.58   7.70   6.333947  4099000

data1 = Nikkei Tokyo Stock Average (8 Desember 2014 - 5 Desember 2019) Jumlah data 1223

data2 = PT. Unilever Indonesia Tbk. Stock (8 Desember 2014 - 5 Desember 2019) Jumlah data 1257

data3 = Singapore Exchange Limited (8 Desember 2014 - 5 Desember 2019) Jumlah data 1249

In [63]:
data1 = data1[['Adj Close']]
print(data1.head())

      Adj Close
0  17935.640625
1  17813.380859
2  17412.580078
3  17257.400391
4  17371.580078


In [64]:
forecast_out = 10
data1['Prediction'] = data1[['Adj Close']].shift(-forecast_out)
print(data1.tail())

         Adj Close  Prediction
1218  23293.910156         NaN
1219  23529.500000         NaN
1220  23379.810547         NaN
1221  23135.230469         NaN
1222  23300.089844         NaN


In [65]:
X = np.array(data1.drop(['Prediction'],1))
X = X[:-forecast_out]
print(X)

[[17935.640625]
 [17813.380859]
 [17412.580078]
 ...
 [23292.650391]
 [23148.570313]
 [23038.580078]]


In [66]:
y = np.array(data1['Prediction'])
y = y[:-forecast_out]
print(y)

[17635.140625 17854.230469 17808.75     ... 23379.810547 23135.230469
 23300.089844]


In [32]:
!pip install quandl

In [0]:
import quandl
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.model_selection import train_test_split

#data dibagi menjadi 80% training dan 20% testing
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2)


In [69]:
#Support Vector Machine (Regressor) 
svr_rbf = SVR(kernel='rbf', C=1e3, gamma=0.1) 
svr_rbf.fit(x_train, y_train)

SVR(C=1000.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma=0.1,
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [70]:
#Testing Model: Score returns the coefficient of determination R^2 of the prediction. 
#The best possible score is 1.0
svm_confidence = svr_rbf.score(x_test, y_test)
print("svm confidence: ", svm_confidence)

svm confidence:  0.33788779678509095


In [71]:
#Create and train the Linear Regression  Model
lr = LinearRegression()
#Train the model
lr.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [72]:
#Testing Model: Score returns the coefficient of determination R^2 of the prediction. 
#The best possible score is 1.0
lr_confidence = lr.score(x_test, y_test)
print("lr confidence: ", lr_confidence)


lr confidence:  0.9141675080820484


In [73]:
#Set x_forecast equal to the last 10 rows of the original data set from Adj Close column
x_forecast = np.array(data1.drop(['Prediction'],1))[-forecast_out:]
print(x_forecast)

[[23112.880859]
 [23292.810547]
 [23373.320313]
 [23437.769531]
 [23409.140625]
 [23293.910156]
 [23529.5     ]
 [23379.810547]
 [23135.230469]
 [23300.089844]]


In [74]:
#Print linear regression model predictions for the next '10' days
lr_prediction = lr.predict(x_forecast)
print(lr_prediction)
# Print support vector regressor model predictions for the next '10' days
svm_prediction = svr_rbf.predict(x_forecast)
print(svm_prediction)

[23011.91512913 23183.33150012 23260.03197168 23321.43179505
 23294.1574568  23184.37908146 23408.82206555 23266.21512228
 23033.20727431 23190.26637946]
[20068.16173743 21187.74330314 20068.16173687 20068.16173687
 20071.17607462 21011.52365624 20068.28435273 20068.16173687
 20086.57593337 20424.47644004]


**DATA 2** 

In [75]:
data2 = data2[['Adj Close']]
print(data2.head())

      Adj Close
0  28040.568359
1  27928.044922
2  27995.562500
3  27815.523438
4  27883.041016


In [76]:
forecast_out = 10
data2['Prediction'] = data2[['Adj Close']].shift(-forecast_out)
print(data2.tail())

         Adj Close  Prediction
1252  41380.539063         NaN
1253  42420.000000         NaN
1254  42675.000000         NaN
1255  42000.000000         NaN
1256  42150.000000         NaN


In [77]:
X2 = np.array(data2.drop(['Prediction'],1))
X2 = X2[:-forecast_out]
print(X2)

[[28040.568359]
 [27928.044922]
 [27995.5625  ]
 ...
 [42370.503906]
 [42123.011719]
 [41603.28125 ]]


In [78]:
y2 = np.array(data2['Prediction'])
y2 = y2[:-forecast_out]
print(y2)

[28355.630859 28355.630859 28378.138672 ... 42675.       42000.
 42150.      ]


In [0]:
#data dibagi menjadi 80% training dan 20% testing
x2_train, x2_test, y2_train, y2_test = train_test_split(X2, y2, test_size=0.2)

In [80]:
#Support Vector Machine (Regressor) 
svr_rbf = SVR(kernel='rbf', C=1e3, gamma=0.1) 
svr_rbf.fit(x2_train, y2_train)

SVR(C=1000.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma=0.1,
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [81]:
#Testing Model: Score returns the coefficient of determination R^2 of the prediction. 
svm_confidence = svr_rbf.score(x2_test, y2_test)
print("svm confidence: ", svm_confidence)

svm confidence:  0.16470636702848407


In [83]:
#Create and train the Linear Regression  Model
lr = LinearRegression()
#Train the model
lr.fit(x2_train, y2_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [84]:
#Testing Model: Score returns the coefficient of determination R^2 of the prediction. 
#The best possible score is 1.0
lr_confidence = lr.score(x2_test, y2_test)
print("lr confidence: ", lr_confidence)

lr confidence:  0.8996225386833822


In [85]:
#Set x_forecast equal to the last 10 rows of the original data set from Adj Close column
x2_forecast = np.array(data2.drop(['Prediction'],1))[-forecast_out:]
print(x_forecast)

[[23112.880859]
 [23292.810547]
 [23373.320313]
 [23437.769531]
 [23409.140625]
 [23293.910156]
 [23529.5     ]
 [23379.810547]
 [23135.230469]
 [23300.089844]]


In [86]:
#Print linear regression model predictions for the next '10' days
lr_prediction = lr.predict(x2_forecast)
print(lr_prediction)
# Print support vector regressor model predictions for the next '10' days
svm_prediction = svr_rbf.predict(x2_forecast)
print(svm_prediction)

[41832.01251393 41762.60230102 41230.47559334 40767.75909856
 41508.10914217 41508.10914217 42479.81560606 42718.19411502
 42087.19217952 42227.41483186]
[42419.90026195 42222.80276541 42064.23135778 42222.80271617
 42222.80262979 42222.80262979 42222.80274115 42222.77446126
 42350.67252107 42222.80271617]


**DATA 3**

In [107]:
data3 = data3[['Adj Close']]
print(data3.head())

   Adj Close
0   6.046041
1   6.251688
2   6.251688
3   6.243463
4   6.333947


In [113]:
forecast_out = 10
data3['Prediction'] = data3[['Adj Close']].shift(-forecast_out)
print(data3.tail())

      Adj Close  Prediction
1244       8.85         NaN
1245       8.93         NaN
1246       8.88         NaN
1247       8.89         NaN
1248       8.92         NaN


In [114]:
X3 = np.array(data3.drop(['Prediction'],1))
X3 = X3[:-forecast_out]
print(X3)

[[6.046041]
 [6.251688]
 [6.251688]
 ...
 [8.86    ]
 [8.9     ]
 [8.83    ]]


In [115]:
y3 = np.array(data3['Prediction'])
y3 = y3[:-forecast_out]
print(y3)

[6.432658 6.407981 6.432658 ... 8.88     8.89     8.92    ]


In [0]:
#data dibagi menjadi 80% training dan 20% testing
x3_train, x3_test, y3_train, y3_test = train_test_split(X3, y3, test_size=0.2)

In [117]:
#Support Vector Machine (Regressor) 
svr_rbf = SVR(kernel='rbf', C=1e3, gamma=0.1) 
svr_rbf.fit(x3_train, y3_train)

SVR(C=1000.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma=0.1,
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [118]:
#Testing Model: Score returns the coefficient of determination R^2 of the prediction. 
svm_confidence = svr_rbf.score(x3_test, y3_test)
print("svm confidence: ", svm_confidence)

svm confidence:  0.8165695014641936


In [119]:
#Create and train the Linear Regression  Model
lr = LinearRegression()
#Train the model
lr.fit(x3_train, y3_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [120]:
#Testing Model: Score returns the coefficient of determination R^2 of the prediction. 
#The best possible score is 1.0
lr_confidence = lr.score(x3_test, y3_test)
print("lr confidence: ", lr_confidence)


lr confidence:  0.8063708294656364


In [121]:
#Set x_forecast equal to the last 10 rows of the original data set from Adj Close column
x3_forecast = np.array(data3.drop(['Prediction'],1))[-forecast_out:]
print(x3_forecast)

[[8.97]
 [8.94]
 [8.64]
 [8.86]
 [8.85]
 [8.85]
 [8.93]
 [8.88]
 [8.89]
 [8.92]]


In [122]:
#Print linear regression model predictions for the next '10' days
lr_prediction3 = lr.predict(x3_forecast)
print(lr_prediction3)
# Print support vector regressor model predictions for the next '10' days
svm_prediction3 = svr_rbf.predict(x3_forecast)
print(svm_prediction3)

[8.90623755 8.87744963 8.58957042 8.80068184 8.79108587 8.79108587
 8.86785366 8.81987379 8.82946976 8.85825769]
[8.84280836 8.82672215 8.63058978 8.78058404 8.77449061 8.77449061
 8.8212114  8.79255532 8.79843253 8.81562678]
